
/*金雨婷 2015/3 点击出现各部门简介*/
$(document).ready(function(){
    $("#btn1").click(function(){
      $("#divImage01").fadeIn();
     
    });
  });
  $(document).ready(function(){
    $("#divImage01").click(function(){
      $("#divImage01").fadeOut();
      $("#divImage02").fadeOut();
      $("#bigdiv").css({"background-image":"url(image/background.jpg)"});
    });
  });
  $(document).ready(function(){
    $("#btn2").click(function(){
      $("#divImage02").fadeIn();
    });
  });
  $(document).ready(function(){
    $("#divImage02").click(function(){
      $("#divImage02").fadeOut();
      $("#bigdiv").css({"background-image":"url(image/background.jpg)"});
    });
  });
  $(document).ready(function(){
    $("#btn3").click(function(){
      $("#divImage03").fadeIn();
  
    });
  });
  $(document).ready(function(){
    $("#divImage03").click(function(){
      $("#divImage03").fadeOut();
      $("#bigdiv").css({"background-image":"url(image/background.jpg)"});
    });
  });
  $(document).ready(function(){
    $("#btn4").click(function(){
      $("#divImage04").fadeIn();
    });
  });
  $(document).ready(function(){
    $("#divImage04").click(function(){
      $("#divImage04").fadeOut();
      $("#bigdiv").css({"background-image":"url(image/background.jpg)"});
    });
  });
  $(document).ready(function(){
    $("#btn5").click(function(){
      $("#divImage05").fadeIn();
    });
  });
  $(document).ready(function(){
    $("#divImage05").click(function(){
      $("#divImage05").fadeOut();
      $("#bigdiv").css({"background-image":"url(image/background.jpg)"});
    });
  });
   $(document).ready(function(){
    $("#btn6").click(function(){
      $("#divImage06").fadeIn();
    });
  });
   $(document).ready(function(){
    $("#divImage06").click(function(){
      $("#divImage06").fadeOut();
      $("#bigdiv").css({"background-image":"url(image/background.jpg)"});
    });
  });